package com.santimattius.kmp.skeleton.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xff3b5184)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFDAE1FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001849)
internal val md_theme_light_secondary = Color(0xff2d4071)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFDAE2FF)
internal val md_theme_light_onSecondaryContainer = Color(0xFF001849)
internal val md_theme_light_tertiary = Color(0xFF006591)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFC9E6FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF001E2F)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFEFBFF)
internal val md_theme_light_onBackground = Color(0xFF1B1B1F)
internal val md_theme_light_surface = Color(0xFFFEFBFF)
internal val md_theme_light_onSurface = Color(0xFF1B1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE2E2EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
internal val md_theme_light_outline = Color(0xFF757680)
internal val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
internal val md_theme_light_inverseSurface = Color(0xFF303034)
internal val md_theme_light_inversePrimary = Color(0xFFB3C5FF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF3C5BA9)
internal val md_theme_light_outlineVariant = Color(0xFFC5C6D0)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val confirmation_color = Color(0xFF00A650)